name: Delete All Tags

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete all tags
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/tags" \
            | jq -r '.[].name' | while read -r tagname ; do
              echo "Deleting tag $tagname"
              curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -X DELETE "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$tagname"
          done
